



FROM node:18-alpine

# #  working directory inside the docker container
# WORKDIR  /app

# # copy package json for caching

# COPY package.json ./
# COPY package-lock.json ./

# # npm install or runtime for your app

# RUN npm install

# # copy rest of the code

# COPY . .

# # now the run command

# CMD ["node", "index.js"]

